@host=http://192.168.0.16:8080/scim/v2
 
###

GET {{host}}/Elements HTTP/1.1
content-type: application/json

###
GET {{host}}/Elements/3290812f-2caf-4f13-9479-d0f620130eda  HTTP/1.1
content-type: application/json

###

GET {{host}}/Elements
    ?filter=urn:ietf:params:scim:schemas:extension:one:2.0:Element.required ge 0
    &startIndex=1
    &count=2
    &sortBy=urn:ietf:params:scim:schemas:extension:one:2.0:Element.required
    &sortOrder=descending